apiVersion: apps/v1
kind: Deployment
metadata:
  name: random-number-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: random-number-service
  template:
    metadata:
      labels:
        app: random-number-service
    spec:
      containers:
      - name: random-number-service
        image: <your-dockerhub-username>/random-number-service:latest
        ports:
        - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: random-number-service
spec:
  selector:
    app: random-number-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
