# Dockerfile

# Usar la imagen base de Node.js
FROM node:14

# Establecer el directorio de trabajo dentro del contenedor
WORKDIR /usr/src/app

# Copiar el archivo package.json y package-lock.json para instalar las dependencias
COPY package*.json ./

# Instalar las dependencias
RUN npm install

# Copiar el código fuente al directorio de trabajo del contenedor
COPY . .

# Exponer el puerto en el que se ejecuta la aplicación
EXPOSE 3002

# Comando para ejecutar la aplicación
CMD ["node", "guess.js"]
