apiVersion: v1
kind: Service
metadata:
  name: guessing-game-service
spec:
  selector:
    app: guessing-game
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: guessing-game-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guessing-game
  template:
    metadata:
      labels:
        app: guessing-game
    spec:
      containers:
      - name: guessing-game-container
        image: tu-imagen-guessing-game
        ports:
        - containerPort: 3002
